# Generated by Django 5.2.5 on 2025-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_data',
                'indexes': [models.Index(fields=['email'], name='otp_data_email_c2f589_idx'), models.Index(fields=['expires_at'], name='otp_data_expires_7f3241_idx')],
            },
        ),
    ]
